#(allow,40)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 40

- name: vm2_allow 1
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_allow
    ignore_errors: yes
    command: iptables -D INPUT -s 10.0.0.42 -j DROP

#(send,39)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 39

- name: vm1_send 2
  hosts: vm1
  tasks:
  - name: vm1_send
    shell: echo "Hello_0" | nc -w 2 10.0.0.51 12345
    ignore_errors: yes