#(open,40)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 40

- name: vm2_open 1
  hosts: vm2
  become: yes
  tasks:
    - name: Start netcat listener
      shell: nc -lk 12345 >> rm_12345_l.txt
      async: 900
      poll: 0
      ignore_errors: true

#(open,21)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 21

- name: vm2_open 2
  hosts: vm2
  become: yes
  tasks:
    - name: Start netcat listener
      shell: nc -lk 12345 >> rm_12345_l.txt
      async: 900
      poll: 0
      ignore_errors: true

#(allow,17)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 17

- name: vm2_allow 3
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_allow
    ignore_errors: yes
    command: iptables -D INPUT -s 10.0.0.42 -j DROP

#(open,43)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 43

- name: vm2_open 4
  hosts: vm2
  become: yes
  tasks:
    - name: Start netcat listener
      shell: nc -lk 12345 >> rm_12345_l.txt
      async: 900
      poll: 0
      ignore_errors: true

#(allow,39)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 39

- name: vm2_allow 5
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_allow
    ignore_errors: yes
    command: iptables -D INPUT -s 10.0.0.42 -j DROP

#(close,43)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 43

- name: vm2_close 6
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_close
    shell: "lsof -i :12345 -t"
    register: nc_pid_1
    async: 900
    poll: 0
    ignore_errors: yes

  - name: vm2_close
    shell: "kill -9 {{ nc_pid_0.stdout }}"
    async: 900
    poll: 0
    ignore_errors: yes
    when: nc_pid_1.stdout != ""

#(open,44)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 44

- name: vm2_open 7
  hosts: vm2
  become: yes
  tasks:
    - name: Start netcat listener
      shell: nc -lk 12345 >> rm_12345_l.txt
      async: 900
      poll: 0
      ignore_errors: true

#(deny,48)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 48

- name: vm2_deny 8
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_deny
    command: iptables -C INPUT -s 10.0.0.42 -j DROP
    register: rule_check0
    async: 900
    poll: 0
    ignore_errors: yes

  - name: vm2_deny
    command: iptables -A INPUT -s 10.0.0.42 -j DROP
    async: 900
    poll: 0
    ignore_errors: yes

#(close,21)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 21

- name: vm2_close 9
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_close
    shell: "lsof -i :12345 -t"
    register: nc_pid_1
    async: 900
    poll: 0
    ignore_errors: yes

  - name: vm2_close
    shell: "kill -9 {{ nc_pid_0.stdout }}"
    async: 900
    poll: 0
    ignore_errors: yes
    when: nc_pid_1.stdout != ""

#(allow,40)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 40

- name: vm2_allow 10
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_allow
    ignore_errors: yes
    command: iptables -D INPUT -s 10.0.0.42 -j DROP

#(allow,44)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 44

- name: vm2_allow 11
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_allow
    ignore_errors: yes
    command: iptables -D INPUT -s 10.0.0.42 -j DROP

#(close,40)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 40

- name: vm2_close 12
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_close
    shell: "lsof -i :12345 -t"
    register: nc_pid_1
    async: 900
    poll: 0
    ignore_errors: yes

  - name: vm2_close
    shell: "kill -9 {{ nc_pid_0.stdout }}"
    async: 900
    poll: 0
    ignore_errors: yes
    when: nc_pid_1.stdout != ""

#(deny,59)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 59

- name: vm2_deny 13
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_deny
    command: iptables -C INPUT -s 10.0.0.42 -j DROP
    register: rule_check0
    async: 900
    poll: 0
    ignore_errors: yes

  - name: vm2_deny
    command: iptables -A INPUT -s 10.0.0.42 -j DROP
    async: 900
    poll: 0
    ignore_errors: yes

#(close,16)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 16

- name: vm2_close 14
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_close
    shell: "lsof -i :12345 -t"
    register: nc_pid_1
    async: 900
    poll: 0
    ignore_errors: yes

  - name: vm2_close
    shell: "kill -9 {{ nc_pid_0.stdout }}"
    async: 900
    poll: 0
    ignore_errors: yes
    when: nc_pid_1.stdout != ""

#(deny,42)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 42

- name: vm2_deny 15
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_deny
    command: iptables -C INPUT -s 10.0.0.42 -j DROP
    register: rule_check0
    async: 900
    poll: 0
    ignore_errors: yes

  - name: vm2_deny
    command: iptables -A INPUT -s 10.0.0.42 -j DROP
    async: 900
    poll: 0
    ignore_errors: yes

#(send,17)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 17

- name: vm1_send 16
  hosts: vm1
  tasks:
  - name: vm1_send
    shell: echo "Hello_0" | nc -w 2 10.0.0.51 12345
    ignore_errors: yes