- name: vm1_open 1
  hosts: vm1
  become: yes
  tasks:
    - name: Start netcat listener in background
      shell: nc -lk 12345 >> rm_12345_l.txt
      async: 900
      poll: 0
      ignore_errors: true

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 15 seconds
      pause:
        seconds: 15

- name: vm1_send 2
  hosts: vm1
  tasks:
    - name: Send Hello_0 message
      shell: echo "Hello_11" | nc -w 2 127.0.0.1 12345
      ignore_errors: yes

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 15 seconds
      pause:
        seconds: 38

- name: vm1_open 3
  hosts: vm1
  become: yes
  tasks:
    - name: Start netcat listener in background
      shell: nohup nc -lk 12345 >> rm_12345_l.txt
      async: 900
      poll: 0
      ignore_errors: true

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 15 seconds
      pause:
        seconds: 13

- name: vm1_send 4
  hosts: vm1
  tasks:
    - name: Send Hello_0 message
      shell: echo "Hello_11" | nc -w 2 127.0.0.1 12345
      ignore_errors: yes