- name: vm1_open 1
  hosts: vm1
  become: yes
  tasks:
    - name: Start netcat listener in background
      shell: nc -lk 12345 >> rm_12345_l.txt
      async: 2
      poll: 1
      ignore_errors: true

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 19 seconds
      pause:
        seconds: 20

- name: vm1_open 2
  hosts: vm1
  become: yes
  tasks:
    - name: Start netcat listener in background
      shell: nc -lk 12345 >> rm_12345_l.txt
      async: 2
      poll: 1
      ignore_errors: true

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 41 seconds
      pause:
        seconds: 42

- name: vm1_open 3
  hosts: vm1
  become: yes
  tasks:
    - name: Start netcat listener in background
      shell: nc -lk 12345 >> rm_12345_l.txt
      async: 2
      poll: 1
      ignore_errors: true

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 41 seconds
      pause:
        seconds: 42

- name: vm1_close 4
  hosts: vm1
  become: yes
  tasks:
  - name: vm1_close 1_1
    shell: "lsof -i :12345 -t"
    register: nc_pid_0
    async: 10
    poll: 1
    ignore_errors: yes

  - name: vm1_close 1_2
    shell: "kill -9 {{ nc_pid_0.stdout }}"
    async: 10
    poll: 1
    ignore_errors: yes
    when: nc_pid_0.stdout != ""

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 41 seconds
      pause:
        seconds: 43

- name: vm1_open 5
  hosts: vm1
  become: yes
  tasks:
    - name: Start netcat listener in background
      shell: nc -lk 12345 >> rm_12345_l.txt
      async: 2
      poll: 1
      ignore_errors: true

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 41 seconds
      pause:
        seconds: 20

- name: vm1_close 6
  hosts: vm1
  become: yes
  tasks:
  - name: vm1_close 1_1
    shell: "lsof -i :12345 -t"
    register: nc_pid_1
    async: 10
    poll: 1
    ignore_errors: yes

  - name: vm1_close 1_2
    shell: "kill -9 {{ nc_pid_0.stdout }}"
    async: 10
    poll: 1
    ignore_errors: yes
    when: nc_pid_1.stdout != ""

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 41 seconds
      pause:
        seconds: 39

- name: vm1_close 7
  hosts: vm1
  become: yes
  tasks:
  - name: vm1_close 1_1
    shell: "lsof -i :12345 -t"
    register: nc_pid_2
    async: 10
    poll: 1
    ignore_errors: yes

  - name: vm1_close 1_2
    shell: "kill -9 {{ nc_pid_0.stdout }}"
    async: 10
    poll: 1
    ignore_errors: yes
    when: nc_pid_2.stdout != ""

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 41 seconds
      pause:
        seconds: 15

- name: vm1_close 8
  hosts: vm1
  become: yes
  tasks:
  - name: vm1_close 1_1
    shell: "lsof -i :12345 -t"
    register: nc_pid_2
    async: 10
    poll: 1
    ignore_errors: yes

  - name: vm1_close 1_2
    shell: "kill -9 {{ nc_pid_0.stdout }}"
    async: 10
    poll: 1
    ignore_errors: yes
    when: nc_pid_2.stdout != ""

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 41 seconds
      pause:
        seconds: 16

- name: vm1_send 9
  hosts: vm1
  tasks:
  - name: vm1_send 2_1
    shell: echo "Hello_0" | nc -w 2 10.0.0.42 12345
    ignore_errors: yes

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 41 seconds
      pause:
        seconds: 39

- name: vm1_open 10
  hosts: vm1
  become: yes
  tasks:
    - name: Start netcat listener in background
      shell: nc -lk 12345 >> rm_12345_l.txt
      async: 2
      poll: 1
      ignore_errors: true

- name: vm1_close 11
  hosts: vm1
  become: yes
  tasks:
  - name: vm1_close 1_1
    shell: "lsof -i :12345 -t"
    register: nc_pid_2
    async: 10
    poll: 1
    ignore_errors: yes

  - name: vm1_close 1_2
    shell: "kill -9 {{ nc_pid_0.stdout }}"
    async: 10
    poll: 1
    ignore_errors: yes
    when: nc_pid_2.stdout != ""

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 41 seconds
      pause:
        seconds: 14

- name: vm1_send 12
  hosts: vm1
  tasks:
  - name: vm1_send 2_1
    shell: echo "Hello_0" | nc -w 2 10.0.0.42 12345
    ignore_errors: yes

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 41 seconds
      pause:
        seconds: 39

- name: vm1_open 13
  hosts: vm1
  become: yes
  tasks:
    - name: Start netcat listener in background
      shell: nc -lk 12345 >> rm_12345_l.txt
      async: 2
      poll: 1
      ignore_errors: true

- name: Wait to ensure listener is up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 41 seconds
      pause:
        seconds: 36

- name: vm1_send 12
  hosts: vm1
  tasks:
  - name: vm1_send 2_1
    shell: echo "Hello_0" | nc -w 2 10.0.0.42 12345
    ignore_errors: yes

- name: vm1_close
  hosts: vm1
  become: yes
  tasks:
  - name: vm1_close 1_1
    shell: "lsof -i :12345 -t"
    register: nc_pid_2
    async: 10
    poll: 1
    ignore_errors: yes

  - name: vm1_close 1_2
    shell: "kill -9 {{ nc_pid_0.stdout }}"
    async: 10
    poll: 1
    ignore_errors: yes
    when: nc_pid_2.stdout != ""