#(open,38)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 38

- name: vm2_open 1
  hosts: vm2
  become: yes
  tasks:
    - name: Start netcat listener
      shell: nc -lk 12345 >> rm_12345_l.txt
      async: 900
      poll: 0
      ignore_errors: true

#(deny,19)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 19

- name: vm2_deny 2
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_deny
    command: iptables -C INPUT -s 10.0.0.42 -j DROP
    register: rule_check0
    async: 900
    poll: 0
    ignore_errors: yes

  - name: vm2_deny
    command: iptables -A INPUT -s 10.0.0.42 -j DROP
    async: 900
    poll: 0
    ignore_errors: yes

#(send,13)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 13

- name: vm1_send 3
  hosts: vm1
  tasks:
  - name: vm1_send
    shell: echo "Hello_0" | nc -w 2 10.0.0.51 12345
    ignore_errors: yes