#(open,38)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 38

- name: vm2_open 1
  hosts: vm2
  become: yes
  tasks:
    - name: Start netcat listener
      shell: nc -lk 12345 >> rm_12345_l.txt
      async: 900
      poll: 0
      ignore_errors: true

#(allow,15)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 15

- name: vm2_allow 2
  hosts: vm2
  become: yes
  tasks:
  - name: vm2_allow
    ignore_errors: yes
    command: iptables -D INPUT -s 10.0.0.42 -j DROP

#(send,35)
- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait
      pause:
        seconds: 35

- name: vm1_send 3
  hosts: vm1
  tasks:
  - name: vm1_send
    shell: echo "Hello_0" | nc -w 2 10.0.0.51 12345
    ignore_errors: yes